// <auto-generated />
using System;
using API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240727160052_add_keyword_review_request_h_index")]
    partial class add_keyword_review_request_h_index
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.Affiliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("UserId");

                    b.ToTable("Affiliation");
                });

            modelBuilder.Entity("API.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abstract")
                        .HasColumnType("text");

                    b.Property<string>("Conclusion")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discussion")
                        .HasColumnType("text");

                    b.Property<string>("DoiNumber")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("Introduction")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("Results")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("API.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Republic of the Congo"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Ivory Coast (Côte d’Ivoire)"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 51,
                            Name = "East Timor (Timor-Leste)"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 54,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 62,
                            Name = "France"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 78,
                            Name = "India"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 91,
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 92,
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Federated States of Micronesia"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Myanmar (Burma)"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 127,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 131,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 152,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 164,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 168,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 185,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 186,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 187,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("API.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Astronomy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Geology"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Anthropology"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Economics"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sociology"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Political Science"
                        },
                        new
                        {
                            Id = 13,
                            Name = "English"
                        },
                        new
                        {
                            Id = 14,
                            Name = "History"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Art History"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Business Administration"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Law School"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Medical School"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Civil Engineering"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Electrical Engineering"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Nursing"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Architecture"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Journalism"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Public Health"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Environmental Science"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Agriculture"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Support"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Research and Development"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Business Development"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Legal"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Product Management"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Services"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Training"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Marine Science"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Meteorology"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Neuroscience"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Biochemistry"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Genetics"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Astrophysics"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Microbiology"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Optics"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Statistics"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Geography"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Criminology"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Social Work"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Urban Studies"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Public Policy"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 57,
                            Name = "French"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Mechanical Engineering"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Communication"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Gender Studies"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Roman Literature"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Greek Literature"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Religious Studies"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Linguistics"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Theatre"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Film Studies"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Comparative Literature"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Dentistry"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Veterinary Medicine"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Mathematics Education"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Science Education"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Foreign Language Education"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Physical Education"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Management"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 84,
                            Name = "International Relations"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Military Science"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Women's Studies"
                        },
                        new
                        {
                            Id = 87,
                            Name = "African Studies"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Asian Studies"
                        },
                        new
                        {
                            Id = 89,
                            Name = "African American Studies"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Latino Studies"
                        },
                        new
                        {
                            Id = 91,
                            Name = "LGBTQ+ Studies"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Disability Studies"
                        });
                });

            modelBuilder.Entity("API.Entities.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name", "CountryId")
                        .IsUnique();

                    b.ToTable("Institution");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 9,
                            Name = "Australian Catholic University"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 9,
                            Name = "Australian National University"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 9,
                            Name = "Avondale University"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 9,
                            Name = "Bond University"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 9,
                            Name = "Central Queensland University"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 9,
                            Name = "Charles Darwin University"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 9,
                            Name = "Charles Sturt University"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 9,
                            Name = "Curtin University"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 9,
                            Name = "Deakin University"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 9,
                            Name = "Edith Cowan University"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 9,
                            Name = "Federation University Australia"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 9,
                            Name = "Flinders University"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 9,
                            Name = "Griffith University"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 9,
                            Name = "James Cook University"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 9,
                            Name = "La Trobe University"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 9,
                            Name = "Macquarie University"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 9,
                            Name = "Monash University"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 9,
                            Name = "Murdoch University"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 9,
                            Name = "Queensland University of Technology"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 9,
                            Name = "RMIT University"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 9,
                            Name = "Southern Cross University"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 9,
                            Name = "Swinburne University of Technology"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 9,
                            Name = "The University of Adelaide"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 9,
                            Name = "The University of Melbourne"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 9,
                            Name = "The University of Newcastle"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 9,
                            Name = "The University of Notre Dame Australia"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 9,
                            Name = "The University of Queensland"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 9,
                            Name = "The University of Sydney"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 9,
                            Name = "The University of Western Australia"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 9,
                            Name = "Torrens University Australia"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 9,
                            Name = "University of Canberra"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 9,
                            Name = "University of Divinity"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 9,
                            Name = "University of New England"
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 9,
                            Name = "University of New South Wales"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 9,
                            Name = "University of South Australia"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 9,
                            Name = "University of Southern Queensland"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 9,
                            Name = "University of Tasmania"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 9,
                            Name = "University of Technology Sydney"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 9,
                            Name = "University of the Sunshine Coast"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 9,
                            Name = "University of Wollongong"
                        },
                        new
                        {
                            Id = 41,
                            CountryId = 9,
                            Name = "Victoria University"
                        },
                        new
                        {
                            Id = 42,
                            CountryId = 193,
                            Name = "Hanoi University of Science and Technology"
                        },
                        new
                        {
                            Id = 43,
                            CountryId = 193,
                            Name = "School of Information and Communication Technology"
                        },
                        new
                        {
                            Id = 44,
                            CountryId = 193,
                            Name = "School of Material Science"
                        },
                        new
                        {
                            Id = 45,
                            CountryId = 193,
                            Name = "School of Mechanical Engineering"
                        },
                        new
                        {
                            Id = 46,
                            CountryId = 193,
                            Name = "School of Chemistry and Life Science"
                        },
                        new
                        {
                            Id = 47,
                            CountryId = 193,
                            Name = "School of Electrical and Electronic Engineering"
                        },
                        new
                        {
                            Id = 48,
                            CountryId = 193,
                            Name = "University of Economics Ho Chi Minh City"
                        },
                        new
                        {
                            Id = 49,
                            CountryId = 193,
                            Name = "College of Business"
                        },
                        new
                        {
                            Id = 50,
                            CountryId = 193,
                            Name = "College of Economics, Law and Gorvernment"
                        },
                        new
                        {
                            Id = 51,
                            CountryId = 193,
                            Name = "College of Technology and Design"
                        },
                        new
                        {
                            Id = 52,
                            CountryId = 193,
                            Name = "Vietnam National University, Hanoi"
                        },
                        new
                        {
                            Id = 53,
                            CountryId = 193,
                            Name = "University of Engineering and Technology"
                        },
                        new
                        {
                            Id = 54,
                            CountryId = 193,
                            Name = "University of Sciences"
                        },
                        new
                        {
                            Id = 55,
                            CountryId = 193,
                            Name = "University of Social Sciences and Humanities"
                        },
                        new
                        {
                            Id = 56,
                            CountryId = 193,
                            Name = "University of Economics and Business"
                        },
                        new
                        {
                            Id = 57,
                            CountryId = 193,
                            Name = "University of Medicine and Pharmacy"
                        },
                        new
                        {
                            Id = 58,
                            CountryId = 193,
                            Name = "University of Law"
                        },
                        new
                        {
                            Id = 59,
                            CountryId = 193,
                            Name = "Vietnam–Japan University"
                        },
                        new
                        {
                            Id = 60,
                            CountryId = 193,
                            Name = "International School"
                        },
                        new
                        {
                            Id = 61,
                            CountryId = 193,
                            Name = "School of Business and Management"
                        },
                        new
                        {
                            Id = 62,
                            CountryId = 193,
                            Name = "School of Interdisciplinary Sciences"
                        },
                        new
                        {
                            Id = 63,
                            CountryId = 193,
                            Name = "Vietnam National University, Ho Chi Minh City"
                        },
                        new
                        {
                            Id = 64,
                            CountryId = 193,
                            Name = "University of Technology"
                        },
                        new
                        {
                            Id = 65,
                            CountryId = 193,
                            Name = "University of Science"
                        },
                        new
                        {
                            Id = 66,
                            CountryId = 193,
                            Name = "Ho Chi Minh City University of Technology and Education"
                        },
                        new
                        {
                            Id = 67,
                            CountryId = 193,
                            Name = "International University"
                        },
                        new
                        {
                            Id = 68,
                            CountryId = 193,
                            Name = "University of Economics and Law"
                        },
                        new
                        {
                            Id = 69,
                            CountryId = 193,
                            Name = "University of Information Technology"
                        },
                        new
                        {
                            Id = 70,
                            CountryId = 193,
                            Name = "School of Medicine"
                        },
                        new
                        {
                            Id = 71,
                            CountryId = 193,
                            Name = "School of Political and Administration Sciences"
                        },
                        new
                        {
                            Id = 72,
                            CountryId = 193,
                            Name = "Institute of Environment and Resource"
                        },
                        new
                        {
                            Id = 73,
                            CountryId = 193,
                            Name = "Foreign Trade University"
                        },
                        new
                        {
                            Id = 74,
                            CountryId = 193,
                            Name = "Hanoi University of Mining and Geology"
                        },
                        new
                        {
                            Id = 75,
                            CountryId = 193,
                            Name = "Hanoi National University of Education"
                        },
                        new
                        {
                            Id = 76,
                            CountryId = 193,
                            Name = "Hanoi University of Industrial Fine Arts"
                        },
                        new
                        {
                            Id = 77,
                            CountryId = 193,
                            Name = "National Academy of Education Management"
                        },
                        new
                        {
                            Id = 78,
                            CountryId = 193,
                            Name = "University of Transportation and Communication"
                        },
                        new
                        {
                            Id = 79,
                            CountryId = 193,
                            Name = "National Economics University"
                        },
                        new
                        {
                            Id = 80,
                            CountryId = 193,
                            Name = "University of Education"
                        },
                        new
                        {
                            Id = 81,
                            CountryId = 193,
                            Name = "University of Languages and International Studies"
                        });
                });

            modelBuilder.Entity("API.Entities.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("API.Entities.Reference", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("ReferenceArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArticleId", "ReferenceArticleId");

                    b.HasIndex("ReferenceArticleId");

                    b.ToTable("References");
                });

            modelBuilder.Entity("API.Entities.ReviewRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("ArticleId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("ReviewRequests");
                });

            modelBuilder.Entity("API.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Mental health",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Physics",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Mathematics",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Computer Science",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Chemistry",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Engineering",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Agriculture",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Medicine",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Pharmacology",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Biology",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Biotechnology",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Biomedical Application",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Geography",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Geology",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Geophysics",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Oceanography",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Ecology",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Climatology",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TopicName = "Nutrition",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ArticleKeyword", b =>
                {
                    b.Property<int>("ArticlesId")
                        .HasColumnType("integer");

                    b.Property<int>("KeywordsId")
                        .HasColumnType("integer");

                    b.HasKey("ArticlesId", "KeywordsId");

                    b.HasIndex("KeywordsId");

                    b.ToTable("ArticleKeyword");
                });

            modelBuilder.Entity("ArticleTopic", b =>
                {
                    b.Property<int>("ArticlesId")
                        .HasColumnType("integer");

                    b.Property<int>("TopicsId")
                        .HasColumnType("integer");

                    b.HasKey("ArticlesId", "TopicsId");

                    b.HasIndex("TopicsId");

                    b.ToTable("ArticleTopic");
                });

            modelBuilder.Entity("ArticleUser", b =>
                {
                    b.Property<int>("ArticlesId")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorsId")
                        .HasColumnType("integer");

                    b.HasKey("ArticlesId", "AuthorsId");

                    b.HasIndex("AuthorsId");

                    b.ToTable("ArticleUser");
                });

            modelBuilder.Entity("API.Entities.Affiliation", b =>
                {
                    b.HasOne("API.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.User", null)
                        .WithMany("Affiliations")
                        .HasForeignKey("UserId");

                    b.Navigation("Department");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("API.Entities.Institution", b =>
                {
                    b.HasOne("API.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("API.Entities.Reference", b =>
                {
                    b.HasOne("API.Entities.Article", "Article")
                        .WithMany("CitationBy")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Entities.Article", "ReferenceArticle")
                        .WithMany("References")
                        .HasForeignKey("ReferenceArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("ReferenceArticle");
                });

            modelBuilder.Entity("API.Entities.ReviewRequest", b =>
                {
                    b.HasOne("API.Entities.Article", "Article")
                        .WithMany("ReviewRequests")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("ArticleKeyword", b =>
                {
                    b.HasOne("API.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArticleTopic", b =>
                {
                    b.HasOne("API.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArticleUser", b =>
                {
                    b.HasOne("API.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Entities.Article", b =>
                {
                    b.Navigation("CitationBy");

                    b.Navigation("References");

                    b.Navigation("ReviewRequests");
                });

            modelBuilder.Entity("API.Entities.User", b =>
                {
                    b.Navigation("Affiliations");
                });
#pragma warning restore 612, 618
        }
    }
}
