using Microsoft.EntityFrameworkCore;

namespace API.Entities {
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions options) : base(options)
        {
        }

        public virtual DbSet<User> Users {get; set;}
        public virtual DbSet<Article> Articles {get; set;}
        public virtual DbSet<Topic> Topics {get; set;}
        public virtual DbSet<Reference> References {get; set;}
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Reference>().HasKey(reference => new {reference.ArticleId, reference.ReferenceArticleId});
            modelBuilder.Entity<Reference>()
                .HasOne(reference => reference.Article)
                .WithMany(article => article.CitationBy)
                .HasForeignKey(reference => reference.ArticleId)
                .OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Reference>()
                .HasOne(reference => reference.ReferenceArticle)
                .WithMany(article => article.References)
                .HasForeignKey(reference => reference.ReferenceArticleId)
                .OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Institution>()
                .HasIndex(institution => new {institution.Name, institution.CountryId})
                .IsUnique();
            InitializeTestData(modelBuilder);
        }

        private void InitializeTestData(ModelBuilder modelBuilder) {

            #region Topics data
            modelBuilder.Entity<Topic>().HasData(
                new Topic() {Id = 1, TopicName = "Mental health"},
                new Topic {Id = 2, TopicName = "Physics"},
                new Topic {Id = 3, TopicName = "Mathematics"},
                new Topic {Id = 4, TopicName = "Computer Science"},
                new Topic {Id = 5, TopicName = "Chemistry"},
                new Topic {Id = 6, TopicName = "Engineering"},
                new Topic {Id = 7, TopicName = "Agriculture"},
                new Topic {Id = 8, TopicName = "Medicine"},
                new Topic {Id = 9, TopicName = "Pharmacology"},
                new Topic {Id = 10, TopicName = "Biology"},
                new Topic {Id = 11, TopicName = "Biotechnology"},
                new Topic {Id = 12, TopicName = "Biomedical Application"},
                new Topic {Id = 13, TopicName = "Geography"},
                new Topic {Id = 14, TopicName = "Geology"},
                new Topic {Id = 15, TopicName = "Geophysics"},
                new Topic {Id = 16, TopicName = "Oceanography"},
                new Topic {Id = 17, TopicName = "Ecology"},
                new Topic {Id = 18, TopicName = "Climatology"},
                new Topic {Id = 19, TopicName = "Nutrition"}
            );
            #endregion

            #region Departments data
            modelBuilder.Entity<Department>().HasData(
                new Department {Id = 1, Name = "Biology"},
                new Department {Id = 2, Name = "Chemistry"},
                new Department {Id = 3, Name = "Physics"},
                new Department {Id = 4, Name = "Astronomy"},
                new Department {Id = 5, Name = "Geology"},
                new Department {Id = 6, Name = "Mathematics"},
                new Department {Id = 7, Name = "Computer Science"},
                new Department {Id = 8, Name = "Anthropology"},
                new Department {Id = 9, Name = "Economics"},
                new Department {Id = 10, Name = "Psychology"},
                new Department {Id = 11, Name = "Sociology"},
                new Department {Id = 12, Name = "Political Science"},
                new Department {Id = 13, Name = "English"},
                new Department {Id = 14, Name = "History"},
                new Department {Id = 15, Name = "Philosophy"},
                new Department {Id = 16, Name = "Art History"},
                new Department {Id = 17, Name = "Music"},
                new Department {Id = 18, Name = "Business Administration"},
                new Department {Id = 19, Name = "Law School"},
                new Department {Id = 20, Name = "Medical School"},
                new Department {Id = 21, Name = "Civil Engineering"},
                new Department {Id = 22, Name = "Electrical Engineering"},
                new Department {Id = 23, Name = "Software Engineering"},
                new Department {Id = 24, Name = "Nursing"},
                new Department {Id = 25, Name = "Education"},
                new Department {Id = 26, Name = "Architecture"},
                new Department {Id = 27, Name = "Journalism"},
                new Department {Id = 28, Name = "Public Health"},
                new Department {Id = 29, Name = "Environmental Science"},
                new Department {Id = 30, Name = "Agriculture"},
                new Department {Id = 31, Name = "Human Resources"},
                new Department {Id = 32, Name = "Support"},
                new Department {Id = 33, Name = "Research and Development"},
                new Department {Id = 34, Name = "Accounting"},
                new Department {Id = 35, Name = "Sales"},
                new Department {Id = 36, Name = "Business Development"},
                new Department {Id = 37, Name = "Marketing"},
                new Department {Id = 38, Name = "Legal"},
                new Department {Id = 39, Name = "Product Management"},
                new Department {Id = 40, Name = "Services"},
                new Department {Id = 41, Name = "Training"},
                new Department {Id = 42, Name = "Marine Science"},
                new Department {Id = 43, Name = "Meteorology"},
                new Department {Id = 44, Name = "Neuroscience"},
                new Department {Id = 45, Name = "Biochemistry"},
                new Department {Id = 46, Name = "Genetics"},
                new Department {Id = 47, Name = "Astrophysics"},
                new Department {Id = 48, Name = "Microbiology"},
                new Department {Id = 49, Name = "Optics"},
                new Department {Id = 50, Name = "Statistics"},
                new Department {Id = 51, Name = "Geography"},
                new Department {Id = 52, Name = "Criminology"},
                new Department {Id = 53, Name = "Social Work"},
                new Department {Id = 54, Name = "Urban Studies"},
                new Department {Id = 55, Name = "Public Policy"},
                new Department {Id = 56, Name = "Spanish"},
                new Department {Id = 57, Name = "French"},
                new Department {Id = 58, Name = "Chinese"},
                new Department {Id = 59, Name = "Arabic"},
                new Department {Id = 60, Name = "Mechanical Engineering"},
                new Department {Id = 61, Name = "Communication"},
                new Department {Id = 62, Name = "Gender Studies"},
                new Department {Id = 63, Name = "Cybersecurity"},
                new Department {Id = 64, Name = "Information Technology"},
                new Department {Id = 65, Name = "Roman Literature"},
                new Department {Id = 66, Name = "Greek Literature"},
                new Department {Id = 67, Name = "Religious Studies"},
                new Department {Id = 69, Name = "Linguistics"},
                new Department {Id = 70, Name = "Theatre"},
                new Department {Id = 71, Name = "Film Studies"},
                new Department {Id = 72, Name = "Comparative Literature"},
                new Department {Id = 73, Name = "Pharmacy"},
                new Department {Id = 74, Name = "Dentistry"},
                new Department {Id = 75, Name = "Veterinary Medicine"},
                new Department {Id = 76, Name = "Mathematics Education"},
                new Department {Id = 77, Name = "Science Education"},
                new Department {Id = 78, Name = "Foreign Language Education"},
                new Department {Id = 79, Name = "Physical Education"},
                new Department {Id = 80, Name = "Data Science"},
                new Department {Id = 81, Name = "Artificial Intelligence"},
                new Department {Id = 82, Name = "Management"},
                new Department {Id = 83, Name = "Finance"},
                new Department {Id = 84, Name = "International Relations"},
                new Department {Id = 85, Name = "Military Science"},
                new Department {Id = 86, Name = "Women's Studies"},
                new Department {Id = 87, Name = "African Studies"},
                new Department {Id = 88, Name = "Asian Studies"},
                new Department {Id = 89, Name = "African American Studies"},
                new Department {Id = 90, Name = "Latino Studies"},
                new Department {Id = 91, Name = "LGBTQ+ Studies"},
                new Department {Id = 92, Name = "Disability Studies"}
            );
            #endregion

            #region Countries data
            modelBuilder.Entity<Country>().HasData(
                new Country {Id = 1, Name = "Afghanistan"},
                new Country {Id = 2, Name = "Albania"},
                new Country {Id = 3, Name = "Algeria"},
                new Country {Id = 4, Name = "Andorra"},
                new Country {Id = 5, Name = "Angola"},
                new Country {Id = 6, Name = "Antigua and Barbuda"},
                new Country {Id = 7, Name = "Argentina"},
                new Country {Id = 8, Name = "Armenia"},
                new Country {Id = 9, Name = "Australia"},
                new Country {Id = 10, Name = "Austria"},
                new Country {Id = 11, Name = "Azerbaijan"},
                new Country {Id = 12, Name = "Bahamas"},
                new Country {Id = 13, Name = "Bahrain"},
                new Country {Id = 14, Name = "Bangladesh"},
                new Country {Id = 15, Name = "Barbados"},
                new Country {Id = 16, Name = "Belarus"},
                new Country {Id = 17, Name = "Belgium"},
                new Country {Id = 18, Name = "Belize"},
                new Country {Id = 19, Name = "Benin"},
                new Country {Id = 20, Name = "Bhutan"},
                new Country {Id = 21, Name = "Bolivia"},
                new Country {Id = 22, Name = "Bosnia and Herzegovina"},
                new Country {Id = 23, Name = "Botswana"},
                new Country {Id = 24, Name = "Brazil"},
                new Country {Id = 25, Name = "Brunei"},
                new Country {Id = 26, Name = "Bulgaria"},
                new Country {Id = 27, Name = "Burkina Faso"},
                new Country {Id = 28, Name = "Burundi"},
                new Country {Id = 29, Name = "Cabo Verde"},
                new Country {Id = 30, Name = "Cambodia"},
                new Country {Id = 31, Name = "Cameroon"},
                new Country {Id = 32, Name = "Canada"},
                new Country {Id = 33, Name = "Central African Republic"},
                new Country {Id = 34, Name = "Chad"},
                new Country {Id = 35, Name = "Chile"},
                new Country {Id = 36, Name = "China"},
                new Country {Id = 37, Name = "Colombia"},
                new Country {Id = 38, Name = "Comoros"},
                new Country {Id = 39, Name = "Democratic Republic of the Congo"},
                new Country {Id = 40, Name = "Republic of the Congo"},
                new Country {Id = 41, Name = "Costa Rica"},
                new Country {Id = 42, Name = "Ivory Coast (Côte d’Ivoire)"},
                new Country {Id = 43, Name = "Croatia"},
                new Country {Id = 44, Name = "Cuba"},
                new Country {Id = 45, Name = "Cyprus"},
                new Country {Id = 46, Name = "Czech Republic"},
                new Country {Id = 47, Name = "Denmark"},
                new Country {Id = 48, Name = "Djibouti"},
                new Country {Id = 49, Name = "Dominica"},
                new Country {Id = 50, Name = "Dominican Republic"},
                new Country {Id = 51, Name = "East Timor (Timor-Leste)"},
                new Country {Id = 52, Name = "Ecuador"},
                new Country {Id = 53, Name = "Egypt"},
                new Country {Id = 54, Name = "El Salvador"},
                new Country {Id = 55, Name = "Equatorial Guinea"},
                new Country {Id = 56, Name = "Eritrea"},
                new Country {Id = 57, Name = "Estonia"},
                new Country {Id = 58, Name = "Eswatini"},
                new Country {Id = 59, Name = "Ethiopia"},
                new Country {Id = 60, Name = "Fiji"},
                new Country {Id = 61, Name = "Finland"},
                new Country {Id = 62, Name = "France"},
                new Country {Id = 63, Name = "Gabon"},
                new Country {Id = 64, Name = "Gambia"},
                new Country {Id = 65, Name = "Georgia"},
                new Country {Id = 66, Name = "Germany"},
                new Country {Id = 67, Name = "Ghana"},
                new Country {Id = 68, Name = "Greece"},
                new Country {Id = 69, Name = "Grenada"},
                new Country {Id = 70, Name = "Guatemala"},
                new Country {Id = 71, Name = "Guinea"},
                new Country {Id = 72, Name = "Guinea-Bissau"},
                new Country {Id = 73, Name = "Guyana"},
                new Country {Id = 74, Name = "Haiti"},
                new Country {Id = 75, Name = "Honduras"},
                new Country {Id = 76, Name = "Hungary"},
                new Country {Id = 77, Name = "Iceland"},
                new Country {Id = 78, Name = "India"},
                new Country {Id = 79, Name = "Indonesia"},
                new Country {Id = 80, Name = "Iran"},
                new Country {Id = 81, Name = "Iraq"},
                new Country {Id = 82, Name = "Ireland"},
                new Country {Id = 83, Name = "Israel"},
                new Country {Id = 84, Name = "Italy"},
                new Country {Id = 85, Name = "Jamaica"},
                new Country {Id = 86, Name = "Japan"},
                new Country {Id = 87, Name = "Jordan"},
                new Country {Id = 88, Name = "Kazakhstan"},
                new Country {Id = 89, Name = "Kenya"},
                new Country {Id = 90, Name = "Kiribati"},
                new Country {Id = 91, Name = "North Korea"},
                new Country {Id = 92, Name = "South Korea"},
                new Country {Id = 93, Name = "Kosovo"},
                new Country {Id = 94, Name = "Kuwait"},
                new Country {Id = 95, Name = "Kyrgyzstan"},
                new Country {Id = 96, Name = "Laos"},
                new Country {Id = 97, Name = "Latvia"},
                new Country {Id = 98, Name = "Lebanon"},
                new Country {Id = 99, Name = "Lesotho"},
                new Country {Id = 100, Name = "Liberia"},
                new Country {Id = 101, Name = "Libya"},
                new Country {Id = 102, Name = "Liechtenstein"},
                new Country {Id = 103, Name = "Lithuania"},
                new Country {Id = 104, Name = "Luxembourg"},
                new Country {Id = 105, Name = "Madagascar"},
                new Country {Id = 106, Name = "Malawi"},
                new Country {Id = 107, Name = "Malaysia"},
                new Country {Id = 108, Name = "Maldives"},
                new Country {Id = 109, Name = "Mali"},
                new Country {Id = 110, Name = "Malta"},
                new Country {Id = 111, Name = "Marshall Islands"},
                new Country {Id = 112, Name = "Mauritania"},
                new Country {Id = 113, Name = "Mauritius"},
                new Country {Id = 114, Name = "Mexico"},
                new Country {Id = 115, Name = "Federated States of Micronesia"},
                new Country {Id = 116, Name = "Moldova"},
                new Country {Id = 117, Name = "Monaco"},
                new Country {Id = 118, Name = "Mongolia"},
                new Country {Id = 119, Name = "Montenegro"},
                new Country {Id = 120, Name = "Morocco"},
                new Country {Id = 121, Name = "Mozambique"},
                new Country {Id = 122, Name = "Myanmar (Burma)"},
                new Country {Id = 123, Name = "Namibia"},
                new Country {Id = 124, Name = "Nauru"},
                new Country {Id = 125, Name = "Nepal"},
                new Country {Id = 126, Name = "Netherlands"},
                new Country {Id = 127, Name = "New Zealand"},
                new Country {Id = 128, Name = "Nicaragua"},
                new Country {Id = 129, Name = "Niger"},
                new Country {Id = 130, Name = "Nigeria"},
                new Country {Id = 131, Name = "North Macedonia"},
                new Country {Id = 132, Name = "Norway"},
                new Country {Id = 133, Name = "Oman"},
                new Country {Id = 134, Name = "Pakistan"},
                new Country {Id = 135, Name = "Palau"},
                new Country {Id = 136, Name = "Palestine"},
                new Country {Id = 137, Name = "Panama"},
                new Country {Id = 138, Name = "Papua New Guinea"},
                new Country {Id = 139, Name = "Paraguay"},
                new Country {Id = 140, Name = "Peru"},
                new Country {Id = 141, Name = "Philippines"},
                new Country {Id = 142, Name = "Poland"},
                new Country {Id = 143, Name = "Portugal"},
                new Country {Id = 144, Name = "Qatar"},
                new Country {Id = 145, Name = "Romania"},
                new Country {Id = 146, Name = "Russia"},
                new Country {Id = 147, Name = "Rwanda"},
                new Country {Id = 148, Name = "Saint Kitts and Nevis"},
                new Country {Id = 149, Name = "Saint Lucia"},
                new Country {Id = 150, Name = "Saint Vincent and the Grenadines"},
                new Country {Id = 151, Name = "Samoa"},
                new Country {Id = 152, Name = "San Marino"},
                new Country {Id = 153, Name = "Sao Tome and Principe"},
                new Country {Id = 154, Name = "Saudi Arabia"},
                new Country {Id = 155, Name = "Senegal"},
                new Country {Id = 156, Name = "Serbia"},
                new Country {Id = 157, Name = "Seychelles"},
                new Country {Id = 158, Name = "Sierra Leone"},
                new Country {Id = 159, Name = "Singapore"},
                new Country {Id = 160, Name = "Slovakia"},
                new Country {Id = 161, Name = "Slovenia"},
                new Country {Id = 162, Name = "Solomon Islands"},
                new Country {Id = 163, Name = "Somalia"},
                new Country {Id = 164, Name = "South Africa"},
                new Country {Id = 165, Name = "Spain"},
                new Country {Id = 166, Name = "Sri Lanka"},
                new Country {Id = 167, Name = "Sudan"},
                new Country {Id = 168, Name = "South Sudan"},
                new Country {Id = 169, Name = "Suriname"},
                new Country {Id = 170, Name = "Sweden"},
                new Country {Id = 171, Name = "Switzerland"},
                new Country {Id = 172, Name = "Syria"},
                new Country {Id = 173, Name = "Tajikistan"},
                new Country {Id = 174, Name = "Tanzania"},
                new Country {Id = 175, Name = "Thailand"},
                new Country {Id = 176, Name = "Togo"},
                new Country {Id = 177, Name = "Tonga"},
                new Country {Id = 178, Name = "Trinidad and Tobago"},
                new Country {Id = 179, Name = "Tunisia"},
                new Country {Id = 180, Name = "Turkey"},
                new Country {Id = 181, Name = "Turkmenistan"},
                new Country {Id = 182, Name = "Tuvalu"},
                new Country {Id = 183, Name = "Uganda"},
                new Country {Id = 184, Name = "Ukraine"},
                new Country {Id = 185, Name = "United Arab Emirates"},
                new Country {Id = 186, Name = "United Kingdom"},
                new Country {Id = 187, Name = "United States"},
                new Country {Id = 188, Name = "Uruguay"},
                new Country {Id = 189, Name = "Uzbekistan"},
                new Country {Id = 190, Name = "Vanuatu"},
                new Country {Id = 191, Name = "Vatican City"},
                new Country {Id = 192, Name = "Venezuela"},
                new Country {Id = 193, Name = "Vietnam"},
                new Country {Id = 194, Name = "Yemen"},
                new Country {Id = 195, Name = "Zambia"},
                new Country {Id = 196, Name = "Zimbabwe"}
            );
            #endregion
            
            #region Institutions data
            modelBuilder.Entity<Institution>().HasData(
                new Institution { Id = 1, Name = "Australian Catholic University", CountryId = 9},
                new Institution { Id = 2, Name = "Australian National University", CountryId = 9},
                new Institution { Id = 3, Name = "Avondale University", CountryId = 9},
                new Institution { Id = 4, Name = "Bond University", CountryId = 9},
                new Institution { Id = 5, Name = "Central Queensland University", CountryId = 9},
                new Institution { Id = 6, Name = "Charles Darwin University", CountryId = 9},
                new Institution { Id = 7, Name = "Charles Sturt University", CountryId = 9},
                new Institution { Id = 8, Name = "Curtin University", CountryId = 9},
                new Institution { Id = 9, Name = "Deakin University", CountryId = 9},
                new Institution { Id = 10, Name = "Edith Cowan University", CountryId = 9},
                new Institution { Id = 11, Name = "Federation University Australia", CountryId = 9},
                new Institution { Id = 12, Name = "Flinders University", CountryId = 9},
                new Institution { Id = 13, Name = "Griffith University", CountryId = 9},
                new Institution { Id = 14, Name = "James Cook University", CountryId = 9},
                new Institution { Id = 15, Name = "La Trobe University", CountryId = 9},
                new Institution { Id = 16, Name = "Macquarie University", CountryId = 9},
                new Institution { Id = 17, Name = "Monash University", CountryId = 9},
                new Institution { Id = 18, Name = "Murdoch University", CountryId = 9},
                new Institution { Id = 19, Name = "Queensland University of Technology", CountryId = 9},
                new Institution { Id = 20, Name = "RMIT University", CountryId = 9},
                new Institution { Id = 21, Name = "Southern Cross University", CountryId = 9},
                new Institution { Id = 22, Name = "Swinburne University of Technology", CountryId = 9},
                new Institution { Id = 23, Name = "The University of Adelaide", CountryId = 9},
                new Institution { Id = 24, Name = "The University of Melbourne", CountryId = 9},
                new Institution { Id = 25, Name = "The University of Newcastle", CountryId = 9},
                new Institution { Id = 26, Name = "The University of Notre Dame Australia", CountryId = 9},
                new Institution { Id = 27, Name = "The University of Queensland", CountryId = 9},
                new Institution { Id = 28, Name = "The University of Sydney", CountryId = 9},
                new Institution { Id = 29, Name = "The University of Western Australia", CountryId = 9},
                new Institution { Id = 30, Name = "Torrens University Australia", CountryId = 9},
                new Institution { Id = 31, Name = "University of Canberra", CountryId = 9},
                new Institution { Id = 32, Name = "University of Divinity", CountryId = 9},
                new Institution { Id = 33, Name = "University of New England", CountryId = 9},
                new Institution { Id = 34, Name = "University of New South Wales", CountryId = 9},
                new Institution { Id = 35, Name = "University of South Australia", CountryId = 9},
                new Institution { Id = 36, Name = "University of Southern Queensland", CountryId = 9},
                new Institution { Id = 37, Name = "University of Tasmania", CountryId = 9},
                new Institution { Id = 38, Name = "University of Technology Sydney", CountryId = 9},
                new Institution { Id = 39, Name = "University of the Sunshine Coast", CountryId = 9},
                new Institution { Id = 40, Name = "University of Wollongong", CountryId = 9},
                new Institution { Id = 41, Name = "Victoria University", CountryId = 9},
                new Institution { Id = 42, Name = "Hanoi University of Science and Technology", CountryId = 193},
                new Institution { Id = 43, Name = "School of Information and Communication Technology", CountryId = 193},
                new Institution { Id = 44, Name = "School of Material Science", CountryId = 193},
                new Institution { Id = 45, Name = "School of Mechanical Engineering", CountryId = 193},
                new Institution { Id = 46, Name = "School of Chemistry and Life Science", CountryId = 193},
                new Institution { Id = 47, Name = "School of Electrical and Electronic Engineering", CountryId = 193},
                new Institution { Id = 48, Name = "University of Economics Ho Chi Minh City", CountryId = 193},
                new Institution { Id = 49, Name = "College of Business", CountryId = 193},
                new Institution { Id = 50, Name = "College of Economics, Law and Gorvernment", CountryId = 193},
                new Institution { Id = 51, Name = "College of Technology and Design", CountryId = 193},
                new Institution { Id = 52, Name = "Vietnam National University, Hanoi", CountryId = 193},
                new Institution { Id = 53, Name = "University of Engineering and Technology", CountryId = 193},
                new Institution { Id = 54, Name = "University of Sciences", CountryId = 193},
                new Institution { Id = 55, Name = "University of Social Sciences and Humanities", CountryId = 193},
                new Institution { Id = 56, Name = "University of Economics and Business", CountryId = 193},
                new Institution { Id = 57, Name = "University of Medicine and Pharmacy", CountryId = 193},
                new Institution { Id = 58, Name = "University of Law", CountryId = 193},
                new Institution { Id = 59, Name = "Vietnam–Japan University", CountryId = 193},
                new Institution { Id = 60, Name = "International School", CountryId = 193},
                new Institution { Id = 61, Name = "School of Business and Management", CountryId = 193},
                new Institution { Id = 62, Name = "School of Interdisciplinary Sciences", CountryId = 193},
                new Institution { Id = 63, Name = "Vietnam National University, Ho Chi Minh City", CountryId = 193},
                new Institution { Id = 64, Name = "University of Technology", CountryId = 193},
                new Institution { Id = 65, Name = "University of Science", CountryId = 193},
                new Institution { Id = 66, Name = "Ho Chi Minh City University of Technology and Education", CountryId = 193},
                new Institution { Id = 67, Name = "International University", CountryId = 193},
                new Institution { Id = 68, Name = "University of Economics and Law", CountryId = 193},
                new Institution { Id = 69, Name = "University of Information Technology", CountryId = 193},
                new Institution { Id = 70, Name = "School of Medicine", CountryId = 193},
                new Institution { Id = 71, Name = "School of Political and Administration Sciences", CountryId = 193},
                new Institution { Id = 72, Name = "Institute of Environment and Resource", CountryId = 193},
                new Institution { Id = 73, Name = "Foreign Trade University", CountryId = 193},
                new Institution { Id = 74, Name = "Hanoi University of Mining and Geology", CountryId = 193},
                new Institution { Id = 75, Name = "Hanoi National University of Education", CountryId = 193},
                new Institution { Id = 76, Name = "Hanoi University of Industrial Fine Arts", CountryId = 193},
                new Institution { Id = 77, Name = "National Academy of Education Management", CountryId = 193},
                new Institution { Id = 78, Name = "University of Transportation and Communication", CountryId = 193},
                new Institution { Id = 79, Name = "National Economics University", CountryId = 193},
                new Institution { Id = 80, Name = "University of Education", CountryId = 193},
                new Institution { Id = 81, Name = "University of Languages and International Studies", CountryId = 193}
            );
            #endregion
        }
    }
}